version: '3'

services:
  app-server:
    image: registry.cn-zhangjiakou.aliyuncs.com/yangbingdong/polls:0.0.1
    ports:
      - "8080:8080"
    command: ["--spring.cloud.nacos.server-addr=192.168.0.55:8848"]

  app-client:
    image: registry.cn-zhangjiakou.aliyuncs.com/yangbingdong/polls-client:0.0.1
    ports:
      - "8070:80"
    environment:
      API_ENDPOINT: 'http://192.168.0.55:8080'
