apiVersion: v1
kind: Service
metadata:
  name: polls-client
  labels:
    app: polls-client
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: polls-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polls-client
  labels:
    app: polls-client
    version: v1.0
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polls-client
      version: v1.0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: polls-client
        version: v1.0
    spec:
      containers:
        - name: polls-client
          image: registry-vpc.cn-zhangjiakou.aliyuncs.com/yangbingdong/polls-client:0.0.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 10Mi
          env:
            - name: API_ENDPOINT
              value: http://polls:8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: polls-client
  labels:
    app: polls-client
  namespace: prod
spec:
  rules:
    - host: polls.yangbingdong.com
      http:
        paths:
          - path: /
            backend:
              serviceName: polls-client
              servicePort: http