version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always