server:
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://192.168.0.55:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000