boot2:
  app:
    name: polls
    #version: "v1.0"
    image:
      tag: 0.0.1

  args:
    - --spring.cloud.nacos.config.enabled=true
    - --spring.cloud.nacos.server-addr=192.168.0.241:8848
    - --spring.cloud.nacos.config.namespace=prod
  ingress:
    enabled: true
    hosts:
      - polls-server.yangbingdong.com